Feat/test emails
Magometov/scp pull request #24
Opened 2024-05-29 18:53 UTC by Magometov

2024-05-30 17:10 UTC, ruslan-korneev requested changes

2024-05-30 17:10 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +        return link.get("href")
- [regexp](https://regex101.com/)
- jwt_pattern: сам сделаешь
- link_pattern: API_SITE/reverse("users:verfiy") ?token=
- total: {link_pattern}{jwt_pattern

2024-05-30 17:10 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +    mailoutbox: Any,
```python
from django.core.mail import EmailMultiAlternatives

user_create: User
mailoutbox: list[EmailMultiAlternatives]
```

2024-05-30 17:10 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +        {"user_id": str(user.id), "exp": timezone.now() - timedelta(hours=1)}, settings.SECRET_KEY, algorithm="HS256"
[freezegun](https://pypi.org/project/pytest-freezegun/)

2024-05-30 17:10 UTC, ruslan-korneev commented on src/conftest.py
> +def user_data() -> dict[str, str]:
TypedDict

2024-05-31 18:44 UTC, Magometov commented
![image](https://github.com/Magometov/scp/assets/100163663/2911d8f4-b135-442d-85e7-81e11cd9f6ec)
![image](https://github.com/Magometov/scp/assets/100163663/719782a8-e6c5-4c53-ae48-72da757a4260)
Когда прописываю тип возвращаемых данных из функции str | None, получаю данную ошибку, проверял тип возвращаемых данных - это str

2024-05-31 18:45 UTC, Magometov commented
![image](https://github.com/Magometov/scp/assets/100163663/14ac65d8-9858-4062-9bd9-1b5ee178bc79)
Пытался по разному аннотировать , не получилось(

2024-06-01 09:56 UTC, ruslan-korneev requested changes

2024-06-01 09:56 UTC, ruslan-korneev commented on pyproject.toml
> +pytest-freezegun = "^0.4.2"
это dev-зависимость

2024-06-01 09:56 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +    return matches[0] if matches else None
1. `jwt_pattern = r"[\w-]*\.[\w-]*\.[\w-]*"`
2. раздели pattern на несколько читаемых
3. не типизируй return как `Any` никогда
4. используй `re.search(...).group(0)`

2024-06-01 09:56 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +    href = get_link_from_message(str(message.body))
можешь передавать message.body не превращая в str, напиши лучше так:
```python
text = cast(SafeString, message.body)
link = get_link_from_message(text)
```

2024-06-01 09:56 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +    freezer.move_to(initial_datetime + timedelta(days=2))
а что, если мы поменяем в настройках access token lifetime, сделаем 10 дней его живым? везде менять будешь?

2024-06-01 09:56 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +    freezer.move_to(initial_datetime + timedelta(days=2))
кстати, можешь просто timedelta передавать в freezer.move_to
```python
freezer.move_to(timedelta(days=2))
```

2024-06-01 09:56 UTC, ruslan-korneev commented on src/conftest.py
> +def user_create() -> User:
ты забыл переименовать фикстуру

2024-06-01 09:56 UTC, ruslan-korneev commented on src/apps/users/tests/test_users.py
> +    href = get_link_from_message(str(message.body))
```python
from django.utils.safestring import SafeString
```

2024-06-01 10:00 UTC, ruslan-korneev commented
> ![image](https://private-user-images.githubusercontent.com/100163663/335697547-14ac65d8-9858-4062-9bd9-1b5ee178bc79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzYwODQsIm5iZiI6MTcxNzIzNTc4NCwicGF0aCI6Ii8xMDAxNjM2NjMvMzM1Njk3NTQ3LTE0YWM2NWQ4LTk4NTgtNDA2Mi05YmQ5LTFiNWVlMTc4YmM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjY2MTRmYTA5MjhjZDkwOWRjYzlmMDRlNDg5NzczOWFkZWQ0OTlhYTNlNzRmNGEzYjJiZjQ2OWI0ZmYwNGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ageMt1xSnxmlGYpKnAxeCv9fiMPBt0kL_GE56ViH9SM) Пытался по разному аннотировать , не получилось(

```python
if TYPE_CHECKING:
    from freezegun.api import FrozenDateTimeFactory
    
def test_blabla(
    freezer: "FrozenDateTimeFactory",
) -> ...: ...
```

2024-06-01 10:06 UTC, ruslan-korneev commented
> ![image](https://private-user-images.githubusercontent.com/100163663/335697029-2911d8f4-b135-442d-85e7-81e11cd9f6ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzYwODQsIm5iZiI6MTcxNzIzNTc4NCwicGF0aCI6Ii8xMDAxNjM2NjMvMzM1Njk3MDI5LTI5MTFkOGY0LWIxMzUtNDQyZC04NWU3LTgxZTExY2Q5ZjZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWQ0MGY0ZDU0MTdjZTJlYjI4ZTdhNmQ2NTE5ZGI3NGI5NTA0Mjc2YzM1OWIxNjc0Nzc1MGU4MjgwMjM5ZjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XV-Gr_ej35yWqsBjWK_DUPdsTLNxw2HH98pH6YnvgdU) ![image](https://private-user-images.githubusercontent.com/100163663/335697215-719782a8-e6c5-4c53-ae48-72da757a4260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzYwODQsIm5iZiI6MTcxNzIzNTc4NCwicGF0aCI6Ii8xMDAxNjM2NjMvMzM1Njk3MjE1LTcxOTc4MmE4LWU2YzUtNGM1My1hZTQ4LTcyZGE3NTdhNDI2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwOTU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjdkMTIyMzI3MDAwYTgwZGVhOTFhODY4ZTBhMjkyNzI5MjcxYzM5NGI4ODA0ZmU2NGI4OTkwYjE3MjQ5Y2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZOjy7AXRV-SwYC5QFCkTHFlus_PeXNQzRspfxBzelzo) Когда прописываю тип возвращаемых данных из функции str | None, получаю данную ошибку, проверял тип возвращаемых данных - это str


есть несколько вариантов
1. вариант с использованием exception
2. вариант с assert

мы будем юзать здесь вариант с assert:
```python
assert (match := re.search(VERIFICATION_URL_PATTERN, text))
response_from_verify = client.get(match.group(0))
```

удаляешь функцию, выносишь паттерны как константы в этом модуле, и делаешь как я выше написал

2024-06-27 18:16 UTC, merged